version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"