name: Continous Integration Example

on:
  pull_request:
    branches: [ main ]

jobs:
  test_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Python 3.8 environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run our unit tests
      - name: Run unit tests
        run: |
          python test_app.py
